---
- name:  Update the apt indexes and install packages to allow apt to use https repositories
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: install certbot to enable Let’s Encrypt configuration
  apt:
    pkg:
      - certbot
      - python3-certbot-nginx
  
- name: Add Passbolt package official GnuPG key
  ansible.builtin.apt_key:
    keyserver: pgp.mit.edu
    id: "0xDE8B853FC155581D"

- name: Add passbolt repository to your apt lists
  apt_repository:
    repo: "deb https://download.passbolt.com/ce/debian buster stable"
    filename: passbolt
    state: present

- name: Update the apt indexes with the new passbolt apt repository
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install mariadb
  apt:
    pkg:
      - mariadb-server
      - python3-pymysql
      - python-pymysql
    state: latest
- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started
#- name: mysql_root_password
#  mysql_user:
#    user: root
#    check_implicit_admin: true
#    password: "{{ mysql_root_password }}"
#    host: localhost
#- name: remove remote root
#  mysql_user:
#    check_implicit_admin: true
#    login_user: root
#    login_password: "{{ mysql_root_password }}"
#    user: root
#    host: "{{ ansible_fqdn }}"
#    state: absent

- name: Install passbolt
  apt:
    pkg:
      - passbolt-ce-server
  environment:
    DEBIAN_FRONTEND: noninteractive